# NumPy
Numerical Python

In [1]:
import numpy as np

In [2]:
[1, 2, 3, 4]

[1, 2, 3, 4]

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [5]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
a.ndim

2

In [7]:
a.shape

(3, 4)

In [8]:
b = np.array(
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]],
        [[9, 10], [11, 12]]
    ]
)

In [9]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [10]:
b.ndim

3

In [11]:
b.shape

(3, 2, 2)

# Array

```python
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()
```

In [21]:
np.array([1, 2, 3])

array([1, 2, 3])

In [29]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [32]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [45]:
np.empty((2, 2))

array([[4.68207433e-310, 4.68305869e-310],
       [4.68305868e-310, 2.37151510e-322]])

In [46]:
range(5)

range(0, 5)

In [53]:
np.arange(5)

array([0, 1, 2, 3, 4])

### Add, Remove, Sort 

```python
np.append()
np.delete()
np.sort()
```

In [74]:
arr = np.arange(8)
mylist = list(range(8))

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [76]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [77]:
mylist.append([1, 2])

In [78]:
mylist

[0, 1, 2, 3, 4, 5, 6, 7, [1, 2]]

In [79]:
np.append(arr, [[1, 2]])

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [80]:
arr = np.append(arr, [1, 2])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [81]:
np.delete(arr, 1)

array([0, 2, 3, 4, 5, 6, 7, 1, 2])

In [83]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [84]:
np.sort(arr)

array([0, 1, 1, 2, 2, 3, 4, 5, 6, 7])

In [89]:
print("dim", arr.ndim)
print("size", arr.size)
print("shape", arr.shape)

dim 1
size 10
shape (10,)


In [93]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
print("dim", a.ndim)
print("size", a.size)
print("shape", a.shape)

dim 2
size 12
shape (3, 4)


In [95]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [96]:
print("dim", b.ndim)
print("size", b.size)
print("shape", b.shape)

dim 3
size 12
shape (3, 2, 2)


In [97]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [98]:
print("dim", array_example.ndim)
print("size", array_example.size)
print("shape", array_example.shape)

dim 3
size 24
shape (3, 2, 4)


### Reshape

In [99]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [100]:
arr.shape

(10,)

In [101]:
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 1, 2]])

In [103]:
arr.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [1, 2]])

In [109]:
arr3 = arr.reshape(5, 2)

In [110]:
arr3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [1, 2]])

#### Convert 1D to 2D
```python
np.newaxis
np.expand_dims
```

In [119]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [123]:
arr.shape

(10,)

In [133]:
arr4 = arr[np.newaxis, :]

In [134]:
arr4

array([[0, 1, 2, 3, 4, 5, 6, 7, 1, 2]])

In [ ]:
arr4.ndim

2

In [131]:
arr4.shape

(1, 10)

In [145]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [149]:
a.shape

(3, 4)

In [163]:
np.expand_dims(a, axis=0).shape

(1, 3, 4)

In [162]:
a[np.newaxis, :].shape

(1, 3, 4)

## Indexing and Slicing
```
arr[start:stop:step]
```

In [165]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [168]:
arr[8]

1

In [167]:
arr[4:]

array([4, 5, 6, 7, 1, 2])

In [169]:
arr > 2

array([False, False, False,  True,  True,  True,  True,  True, False,
       False])

In [173]:
arr[arr > 2]

array([3, 4, 5, 6, 7])

In [174]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [185]:
a < 8

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [186]:
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [187]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [188]:
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [189]:
a % 3 == 0

array([[False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [194]:
(a % 2 == 0) & (a % 3 == 0)

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [195]:
a[(a % 2 == 0) & (a % 3 == 0)]

array([ 6, 12])

## Creating from Existing Data
```python
np.vstack()
np.hstack()
np.vsplit()
np.hsplit()
.view()
.copy()
```

In [198]:
arr1 = arr[3:8]

In [199]:
arr1

array([3, 4, 5, 6, 7])

In [213]:
a_1 = np.array([[1, 1], [2, 2]])
print(a_1.shape)
a_1

(2, 2)


array([[1, 1],
       [2, 2]])

In [214]:
a_2 = np.array([[3, 3], [4, 4]])
print(a_2.shape)
a_2

(2, 2)


array([[3, 3],
       [4, 4]])

In [215]:
np.vstack([a_1, a_2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [216]:
np.hstack([a_1, a_2])

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [218]:
arrsplit = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [223]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [224]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [225]:
np.hsplit(a, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [230]:
np.vsplit(a, 3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [231]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [233]:
b = a

In [239]:
print(id(a))
print(id(b))
print(id(a) == id(b))

140346352288560
140346352288560
True


In [240]:
b = a.view()

In [241]:
print(id(a))
print(id(b))
print(id(a) == id(b))

140346352288560
140345419381136
False


In [245]:
c = a.copy()

In [247]:
print(id(a))
print(id(c))
print(id(a) == id(c))

140346352288560
140345419370576
False


## Basic Array Operations
```
+
- 
/ 
*
```

In [249]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [251]:
arr + 1

array([1, 2, 3, 4, 5, 6, 7, 8, 2, 3])

In [252]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35,  5, 10])

In [253]:
[1, 2, 3] * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [255]:
[1, 2, 3] + [5]

[1, 2, 3, 5]

In [262]:
arr + np.array([5])

array([ 5,  6,  7,  8,  9, 10, 11, 12,  6,  7])

In [263]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 0.5, 1. ])

In [264]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [271]:
data = np.array([1, 2])
data

array([1, 2])

In [276]:
ones = np.ones(2)
ones

array([1., 1.])

In [277]:
data + ones

array([2., 3.])

In [278]:
data * ones

array([1., 2.])

### Broadcasting

In [279]:
data * 2

array([2, 4])

In [280]:
data + 2

array([3, 4])

### Array Operations
```
data.max()
data.min()
data.sum()
data.mean()
data.std()
data.var()
```

In [ ]:
%%timeit
sum([1, 2, 3, 4])

103 ns ± 3.4 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [ ]:
%%timeit
np.arange(1, 5).sum()

1.98 µs ± 304 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [282]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [285]:
print(arr.sum())
print(arr.max())
print(arr.min())

31
7
0


In [289]:
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

31
7
0


## Matrices

In [293]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [294]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [295]:
np.random.random((3, 2))

array([[0.56248979, 0.98014606],
       [0.53171751, 0.0079114 ],
       [0.03205113, 0.27247885]])

### Matrix Arithmetic

In [304]:
data = np.arange(1, 5).reshape(2, 2)
ones = np.ones((2, 2))
ones_row = np.ones((1, 2))

print(data)
print(ones)
print(ones_row)

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]]


In [300]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [305]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


### Dot Product

In [312]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


```
# perkalian matrix
(2, 3) * (3, 2)  # a_1 * a_2

(3, 2) * (2, 3)  # a_2 * a_1
```

In [313]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [314]:
np.dot(a_2, a_1)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

## Matrix Indexing

In [315]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [319]:
a[0][0]

1

In [320]:
a[1][2]

7

In [321]:
a[2][-1]

12

In [322]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [323]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [324]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [330]:
data.shape

(3, 2)

In [328]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [329]:
print(data.sum(axis=0))
print(data.sum(axis=1))

[ 9 12]
[ 3  7 11]


## Transposing

In [331]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [332]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [335]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [338]:
data.shape

(3, 2)

In [339]:
data.reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [340]:
data.reshape((6, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [343]:
data.reshape((1, 6))

array([[1, 2, 3, 4, 5, 6]])

In [346]:
np.arange(15).reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [365]:
np.linspace(0, 50, num=20).reshape((5, 4))

array([[ 0.        ,  2.63157895,  5.26315789,  7.89473684],
       [10.52631579, 13.15789474, 15.78947368, 18.42105263],
       [21.05263158, 23.68421053, 26.31578947, 28.94736842],
       [31.57894737, 34.21052632, 36.84210526, 39.47368421],
       [42.10526316, 44.73684211, 47.36842105, 50.        ]])

### N Dimensional Array

In [366]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [367]:
ndarr.shape

(2, 2, 2)

In [368]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [378]:
randomarr = np.random.random((4, 3, 2))
randomarr

array([[[0.23945958, 0.04719995],
        [0.16109143, 0.54335714],
        [0.37696618, 0.86575083]],

       [[0.19333205, 0.34762668],
        [0.48194489, 0.28103256],
        [0.12560787, 0.63057813]],

       [[0.7860995 , 0.45998316],
        [0.36842924, 0.54499858],
        [0.26013435, 0.07756629]],

       [[0.98710104, 0.78713768],
        [0.38630058, 0.98807901],
        [0.14710987, 0.56642715]]])

In [379]:
randomarr.flatten()

array([0.23945958, 0.04719995, 0.16109143, 0.54335714, 0.37696618,
       0.86575083, 0.19333205, 0.34762668, 0.48194489, 0.28103256,
       0.12560787, 0.63057813, 0.7860995 , 0.45998316, 0.36842924,
       0.54499858, 0.26013435, 0.07756629, 0.98710104, 0.78713768,
       0.38630058, 0.98807901, 0.14710987, 0.56642715])

In [383]:
randomarr.reshape(-1)

array([0.23945958, 0.04719995, 0.16109143, 0.54335714, 0.37696618,
       0.86575083, 0.19333205, 0.34762668, 0.48194489, 0.28103256,
       0.12560787, 0.63057813, 0.7860995 , 0.45998316, 0.36842924,
       0.54499858, 0.26013435, 0.07756629, 0.98710104, 0.78713768,
       0.38630058, 0.98807901, 0.14710987, 0.56642715])

In [385]:
randomarr.reshape(24,)

array([0.23945958, 0.04719995, 0.16109143, 0.54335714, 0.37696618,
       0.86575083, 0.19333205, 0.34762668, 0.48194489, 0.28103256,
       0.12560787, 0.63057813, 0.7860995 , 0.45998316, 0.36842924,
       0.54499858, 0.26013435, 0.07756629, 0.98710104, 0.78713768,
       0.38630058, 0.98807901, 0.14710987, 0.56642715])

## Math Formulas

In [389]:
# error = (1/n) * np.sum(np.square(observed - prediction))

5.0